import { HotTableProps } from "@handsontable/react-wrapper";

export const config: Partial<HotTableProps> = {
  width: "100%",
  height: "auto",
  nestedHeaders: [
    [
      {
        label: "User",
        colspan: 4,
      },
      {
        label: "Account Details",
        colspan: 3,
      },
      {
        label: "Login information",
        colspan: 2,
      },
    ],
    [
      "Name",
      "Age",
      "Country",
      "City",
      "Active",
      "Interest",
      "Favorite Product",
      "Login date",
      "Login time",
    ],
  ],
  cell: [
    {
      row: 1,
      col: 1,
      comment: {
        value: "A note in a cell",
      },
    },
  ],
  hiddenColumns: {
    indicators: true,
  },
  hiddenRows: {
    indicators: true,
  },
  contextMenu: [
    "cut",
    "copy",
    "---------",
    "row_above",
    "row_below",
    "remove_row",
    "---------",
    "alignment",
    "make_read_only",
    "clear_column",
  ],
  headerClassName: "htLeft",
  colHeaders: true,
  collapsibleColumns: true,
  filters: true,
  dropdownMenu: true,
  comments: true,
  multiColumnSorting: true,
  manualColumnResize: true,
  manualRowMove: true,
  manualRowResize: true,
  autoWrapRow: true,
  rowHeaders: true,
  navigableHeaders: true,
  imeFastEdit: true,
  pagination: true,
  licenseKey: "non-commercial-and-evaluation",
};

export const data = [
  {
    isActive: false,
    name: "Jerry Moen",
    age: 22,
    interest: "Beauty & Personal Care",
    country: "Canada",
    city: "Toronto",
    lastLoginDate: "2025-11-25",
    lastLoginTime: "06:02",
    favoriteProduct: "Elegant Concrete Hat",
  },
  {
    isActive: true,
    name: "Lloyd Auer",
    age: 22,
    interest: "Fashion",
    country: "Australia",
    city: "Sydney",
    lastLoginDate: "2025-12-06",
    lastLoginTime: "13:24",
    favoriteProduct: "Licensed Concrete Pants",
  },
  {
    isActive: true,
    name: "Bob Bahringer II",
    age: 56,
    interest: "Books & Literature",
    country: "UK",
    city: "London",
    lastLoginDate: "2025-08-14",
    lastLoginTime: "08:15",
    favoriteProduct: "Rustic Rubber Mouse",
  },
  {
    isActive: true,
    name: "Adrian Murphy",
    age: 58,
    interest: "Home Decor",
    country: "Germany",
    city: "Walldorf",
    lastLoginDate: "2025-02-07",
    lastLoginTime: "06:40",
    favoriteProduct: "Handcrafted Granite Car",
  },
  {
    isActive: true,
    name: "Juan Yost",
    age: 26,
    interest: "Home Decor",
    country: "Spain",
    city: "Madrid",
    lastLoginDate: "2025-06-22",
    lastLoginTime: "21:44",
    favoriteProduct: "Handmade Bronze Towels",
  },
  {
    isActive: false,
    name: "Brandon Dare",
    age: 32,
    interest: "Fashion",
    country: "China",
    city: "Shenzhen",
    lastLoginDate: "2025-07-20",
    lastLoginTime: "20:12",
    favoriteProduct: "Intelligent Soft Soap",
  },
  {
    isActive: false,
    name: "Laura Reynolds",
    age: 38,
    interest: "Fashion",
    country: "France",
    city: "Lyon",
    lastLoginDate: "2025-02-06",
    lastLoginTime: "02:13",
    favoriteProduct: "Intelligent Plastic Shoes",
  },
  {
    isActive: true,
    name: "Brendan Raynor",
    age: 60,
    interest: "Fashion",
    country: "Netherlands",
    city: "Amsterdam",
    lastLoginDate: "2025-02-10",
    lastLoginTime: "13:56",
    favoriteProduct: "Recycled Concrete Towels",
  },
  {
    isActive: true,
    name: "Audrey Blick",
    age: 50,
    interest: "Fashion",
    country: "Switzerland",
    city: "Zurich",
    lastLoginDate: "2025-05-19",
    lastLoginTime: "21:40",
    favoriteProduct: "Generic Cotton Salad",
  },
  {
    isActive: true,
    name: "Jessie Crona V",
    age: 27,
    interest: "Home Decor",
    country: "Mexico",
    city: "Mexico City",
    lastLoginDate: "2025-12-08",
    lastLoginTime: "17:55",
    favoriteProduct: "Luxurious Granite Cheese",
  },
  {
    isActive: false,
    name: "Mr. Shaun Wolff",
    age: 52,
    interest: "Tech Gadgets",
    country: "Canada",
    city: "Toronto",
    lastLoginDate: "2025-05-02",
    lastLoginTime: "02:16",
    favoriteProduct: "Modern Granite Keyboard",
  },
  {
    isActive: false,
    name: "Mattie Bergnaum",
    age: 28,
    interest: "Fashion",
    country: "Canada",
    city: "Vancouver",
    lastLoginDate: "2025-01-25",
    lastLoginTime: "23:08",
    favoriteProduct: "Oriental Soft Pizza",
  },
];