// Generated by scripts/prepare-container.mjs — do not edit by hand.

// One frozen-install fingerprint per (framework, bucket), all pointing at the
// framework's single seed context: the fingerprint proves the session mounts a
// generator-produced package.json+lock verbatim, and the seeded node_modules
// is only a warm cache the frozen reconciliation adjusts to that lock.
export interface FrameworkDevContext {
  bucket: string;
  bakedKey: string;
  sourceDependencyFingerprint: string;
}

// Container-engine framework -> dev command, port, and baked-deps contexts.
export interface FrameworkDev {
  cmd: string;
  port: number;
  defaultBakedKey: string;
  contexts: FrameworkDevContext[];
}

export const FRAMEWORK_DEV: Record<string, FrameworkDev> = {
  "react-js": { cmd: "pnpm exec vite --host 0.0.0.0 --port 5173", port: 5173, defaultBakedKey: "react-js-18", contexts: [{ bucket: "15", bakedKey: "react-js-18", sourceDependencyFingerprint: "a248f9917226f5f3742c7d7f6342c0d0141831242ebc2b4353c296c87a9650ba" }, { bucket: "16", bakedKey: "react-js-18", sourceDependencyFingerprint: "4e1d7e0165b1bbd0d6974b75368dd30698ce9c229b838224453651ae46b74097" }, { bucket: "17", bakedKey: "react-js-18", sourceDependencyFingerprint: "f0107e94940e97e433ae82991d3f88a7cc7cadf45e88db0c4905b6001a7dfb8e" }, { bucket: "18", bakedKey: "react-js-18", sourceDependencyFingerprint: "f7670143c5c8bf4121f6847d14d36268349731828c34e82c7746c4d989fb8dec" }, { bucket: "next", bakedKey: "react-js-18", sourceDependencyFingerprint: "c448f17e0881303a15e3a3c7484ede8befdb24252b66c194277f6d8d5b6bd7f3" }] },
  "ant-design": { cmd: "pnpm exec vite --host 0.0.0.0 --port 5173", port: 5173, defaultBakedKey: "ant-design-18", contexts: [{ bucket: "17", bakedKey: "ant-design-18", sourceDependencyFingerprint: "791f586d7709189d2d9079695cece10c4b4962fd6037bd90e1c2b92c7a391b8a" }, { bucket: "18", bakedKey: "ant-design-18", sourceDependencyFingerprint: "c4b26a5db69051b182399c9eae7c4ee19644f2b3cda7ded00b14d9e9309ba3ee" }, { bucket: "next", bakedKey: "ant-design-18", sourceDependencyFingerprint: "757618b0fe09bfe658c22c46e56d6f3e8d0527c40cb48aa889e1ef7b3a261cd6" }] },
  "mui": { cmd: "pnpm exec vite --host 0.0.0.0 --port 5173", port: 5173, defaultBakedKey: "mui-18", contexts: [{ bucket: "17", bakedKey: "mui-18", sourceDependencyFingerprint: "51028fcb90e69ec262c491d19c40f3cf1fe33652ce5297741c596f21b17c8476" }, { bucket: "18", bakedKey: "mui-18", sourceDependencyFingerprint: "6b408be400c72788644b882247156f5f9181c8c943cf887cb81407805f192172" }, { bucket: "next", bakedKey: "mui-18", sourceDependencyFingerprint: "ffa91ce5283ecdc8bb22cde3116b0ee6312954d806875c8a57d1521b7b31d20d" }] },
  "base-web": { cmd: "pnpm exec vite --host 0.0.0.0 --port 5173", port: 5173, defaultBakedKey: "base-web-18", contexts: [{ bucket: "17", bakedKey: "base-web-18", sourceDependencyFingerprint: "60816b83244727888b77b86eeaa2978bd81e631fc8d533585562e2dee62113f2" }, { bucket: "18", bakedKey: "base-web-18", sourceDependencyFingerprint: "1b639608dd1c2d6c8825526ee807f0e6cd8c403c540bf245e967e7c68a7b2ec8" }, { bucket: "next", bakedKey: "base-web-18", sourceDependencyFingerprint: "6e515bf22b789c89e6f295e23b07d514caf1e42db9e0fb6682184e2d38b9341e" }] },
  "fluent-ui": { cmd: "pnpm exec vite --host 0.0.0.0 --port 5173", port: 5173, defaultBakedKey: "fluent-ui-18", contexts: [{ bucket: "17", bakedKey: "fluent-ui-18", sourceDependencyFingerprint: "29749bc6a3eec537859e84c22ab3317c7688165f296b4003a75ee0b09f2b2355" }, { bucket: "18", bakedKey: "fluent-ui-18", sourceDependencyFingerprint: "554df14b3dcf0486ba47383d048e013ddfdc2849c9a620c9195d80596a54608d" }, { bucket: "next", bakedKey: "fluent-ui-18", sourceDependencyFingerprint: "2234a40d40ea1a5ca1078ba46a19392daeb9adeba72ac92abb953ada843c52c6" }] },
  "angular": { cmd: "pnpm exec ng serve --host 0.0.0.0 --port 4200", port: 4200, defaultBakedKey: "angular-18", contexts: [{ bucket: "16", bakedKey: "angular-18", sourceDependencyFingerprint: "ba05f9e10ad14542d02bedb21e72d467f9151c90281205013fd6920f41c94b09" }, { bucket: "17", bakedKey: "angular-18", sourceDependencyFingerprint: "6d96ee45098d895505b4253bb065b746b56ceddcfa586a32df8ed5aa35820263" }, { bucket: "18", bakedKey: "angular-18", sourceDependencyFingerprint: "07b88149fca0a9b7de9990f2fae812df1698705b7c801c4327ac8acb77a19504" }, { bucket: "next", bakedKey: "angular-18", sourceDependencyFingerprint: "6a4cdc672121c1e5675ad7c7e64c5630240f7cb0fa40159c570b34bbd8422d64" }] },
  "next.js": { cmd: "pnpm exec next dev -p 3001 -H 0.0.0.0", port: 3001, defaultBakedKey: "next-js-18", contexts: [{ bucket: "15", bakedKey: "next-js-18", sourceDependencyFingerprint: "0d5c0ca2e786b3e59769952dda04a87883b7e2d537f1f36f5188a62105d5bbed" }, { bucket: "16", bakedKey: "next-js-18", sourceDependencyFingerprint: "106f6ab557edbfe35d618669f60361a63214ef836666092ec0f19cb030e605fb" }, { bucket: "17", bakedKey: "next-js-18", sourceDependencyFingerprint: "4976c89a43ebf5b827b4953b43938fb42a8abca09f4afccf7f8db5d5602cb0e9" }, { bucket: "18", bakedKey: "next-js-18", sourceDependencyFingerprint: "2c82e1f3db0173268712bd306e2eefc00e9ef43868862a1f142528f06c246674" }, { bucket: "next", bakedKey: "next-js-18", sourceDependencyFingerprint: "3517a4d146e5af83b66f3e52c76cc16562a97e3adece26cf7b3f13daf71ed038" }] },
  "next-shadcn.js": { cmd: "pnpm exec next dev -p 3001 -H 0.0.0.0", port: 3001, defaultBakedKey: "next-shadcn-js-18", contexts: [{ bucket: "17", bakedKey: "next-shadcn-js-18", sourceDependencyFingerprint: "ce6a5c70adbe921539dfbaeed3547693e2c566d4f603e139422cbdbe81749fb4" }, { bucket: "18", bakedKey: "next-shadcn-js-18", sourceDependencyFingerprint: "aa4368168bd9d709f5b1d63933a084f53fe2df1c691cbe752badcc51f743feb2" }, { bucket: "next", bakedKey: "next-shadcn-js-18", sourceDependencyFingerprint: "1643b41ea0d75b63b879df497ddaea6b1dcf2c7989f37903c152347ebb588e7b" }] },
  "astro": { cmd: "pnpm exec astro dev --host 0.0.0.0 --port 4321", port: 4321, defaultBakedKey: "astro-18", contexts: [{ bucket: "15", bakedKey: "astro-18", sourceDependencyFingerprint: "4627c575f631cff4cd58548f03610a394a458c954f7272c4dcb4cd3be4664bff" }, { bucket: "16", bakedKey: "astro-18", sourceDependencyFingerprint: "f35fc4c788baf35f201440926df552df3a00fa3fd4f577fe7af837b8c86ed348" }, { bucket: "17", bakedKey: "astro-18", sourceDependencyFingerprint: "bfd0a5725d25b9f48afd09fd43dbd639574c5093f674dbc461e1957df2212eed" }, { bucket: "18", bakedKey: "astro-18", sourceDependencyFingerprint: "69fbcc5444f18253369dba52a1ca7c90c881be3037258a02a3d28ee4ab8799a6" }, { bucket: "next", bakedKey: "astro-18", sourceDependencyFingerprint: "d107ef6ac8ac76770453e61c4afc4def42e3f230bf8cee04b7148d836cbc6460" }] },
  "nuxt": { cmd: "pnpm exec nuxt dev --host 0.0.0.0 --port 3001", port: 3001, defaultBakedKey: "nuxt-18", contexts: [{ bucket: "15", bakedKey: "nuxt-18", sourceDependencyFingerprint: "998ab9934750b2d2e32e870637434e1fb786cb7cda33df8b09acc3d521f8b825" }, { bucket: "16", bakedKey: "nuxt-18", sourceDependencyFingerprint: "c353dbf71649494d14b4b81ff8bbd040536264acb6a966ddb07d6d2839bb361f" }, { bucket: "17", bakedKey: "nuxt-18", sourceDependencyFingerprint: "97d3cd6ada8f4e7e8e83fe22faa203cf7806d3d677f84760f690f58657cc75c8" }, { bucket: "18", bakedKey: "nuxt-18", sourceDependencyFingerprint: "43f13f22a2be5238e929d0fe54ee4d56489152e347f9c6df0361a1e32341408e" }, { bucket: "next", bakedKey: "nuxt-18", sourceDependencyFingerprint: "9f8c5ac7c0bfc17a319d2a9023b9e0c4a0e41d8e6ee14cbe551c38e0616cd6f7" }] },
  "remix": { cmd: "pnpm exec remix vite:dev --host 0.0.0.0 --port 5173", port: 5173, defaultBakedKey: "remix-18", contexts: [{ bucket: "15", bakedKey: "remix-18", sourceDependencyFingerprint: "ba54acbf859e8c1283c5f126a1858d6e7559d6bef1658b90f3e06be10f0e161f" }, { bucket: "16", bakedKey: "remix-18", sourceDependencyFingerprint: "7b2bc9909d4cbfee6fe0c6b2ed6e6fb9edf874703cb0d39a09e1b20f82c84d2d" }, { bucket: "17", bakedKey: "remix-18", sourceDependencyFingerprint: "b69759e506bde2e9755bc708071f437b287f488ec21a28f61bad7c53f33f12f9" }, { bucket: "18", bakedKey: "remix-18", sourceDependencyFingerprint: "2cabd4aca3796d6d24fa1c0050d5c2103b867f7904658f034b7c1649f67a7846" }, { bucket: "next", bakedKey: "remix-18", sourceDependencyFingerprint: "7fd51b1859f8f971ac2212015f84277b2bfb579ab5e71505c2fea945aa55181a" }] },
  "vue": { cmd: "pnpm exec vite --host 0.0.0.0 --port 5173", port: 5173, defaultBakedKey: "vue-18", contexts: [{ bucket: "18", bakedKey: "vue-18", sourceDependencyFingerprint: "7adedc579178a45e0b9eb3a4c4c65621c4919918b1ac788800294fabaa973e47" }] },
};

// Build config for the share snapshotter (all examples).
//
// "entry" and "htmlEntry" are the same two paths the catalog hands the browser, carried
// here so the worker can tell whether an agent-supplied index.html actually loads a
// module (DEV-2741). They are the demo's *authored* names — Tier 1 renames TS/JSX on
// its own (toParcelEntry), which is no concern of the build path.
export interface BuildConfig {
  tier: number;
  installCommand: string;
  buildCommand: string;
  outputDir: string;
  outputGlob: string | null;
  entry: string;
  htmlEntry: string | null;
}

export const BUILD_CONFIG: Record<string, BuildConfig> = {
  "blank": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "vite build", outputDir: "dist", outputGlob: null, entry: "/index.js", htmlEntry: "/index.html" },
  "blank-ts": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "vite build", outputDir: "dist", outputGlob: null, entry: "/index.ts", htmlEntry: "/index.html" },
  "blank-react": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "vite build", outputDir: "dist", outputGlob: null, entry: "/src/index.tsx", htmlEntry: "/index.html" },
  "example1": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "tsc && vite build", outputDir: "dist", outputGlob: null, entry: "/index.ts", htmlEntry: "/index.html" },
  "javascript": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "vite build", outputDir: "dist", outputGlob: null, entry: "/index.js", htmlEntry: "/index.html" },
  "typescript": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "tsc && vite build", outputDir: "dist", outputGlob: null, entry: "/index.ts", htmlEntry: "/index.html" },
  "react": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "tsc -b && vite build", outputDir: "dist", outputGlob: null, entry: "/src/index.tsx", htmlEntry: "/index.html" },
  "react-js": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "vite build", outputDir: "dist", outputGlob: null, entry: "/src/index.jsx", htmlEntry: "/index.html" },
  "ant-design": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "vite build", outputDir: "dist", outputGlob: null, entry: "/src/index.jsx", htmlEntry: "/index.html" },
  "mui": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "tsc -b && vite build", outputDir: "dist", outputGlob: null, entry: "/src/index.tsx", htmlEntry: "/index.html" },
  "base-web": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "tsc -b && vite build", outputDir: "dist", outputGlob: null, entry: "/src/index.tsx", htmlEntry: "/index.html" },
  "fluent-ui": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "tsc -b && vite build", outputDir: "dist", outputGlob: null, entry: "/src/index.tsx", htmlEntry: "/index.html" },
  "vue": { tier: 1, installCommand: "pnpm install --frozen-lockfile", buildCommand: "vue-tsc --build --force && vite build", outputDir: "dist", outputGlob: null, entry: "/src/main.ts", htmlEntry: "/index.html" },
  "angular": { tier: 2, installCommand: "pnpm install --frozen-lockfile", buildCommand: "ng build", outputDir: "dist", outputGlob: "dist/*/browser", entry: "/src/main.ts", htmlEntry: "/src/index.html" },
  "next.js": { tier: 2, installCommand: "pnpm install --frozen-lockfile", buildCommand: "next build", outputDir: "out", outputGlob: null, entry: "/app/page.tsx", htmlEntry: null },
  "next-shadcn.js": { tier: 2, installCommand: "pnpm install --frozen-lockfile", buildCommand: "next build", outputDir: "out", outputGlob: null, entry: "/app/page.tsx", htmlEntry: null },
  "astro": { tier: 2, installCommand: "pnpm install --frozen-lockfile", buildCommand: "astro build", outputDir: "dist", outputGlob: null, entry: "/src/pages/index.astro", htmlEntry: null },
  "nuxt": { tier: 2, installCommand: "pnpm install --frozen-lockfile", buildCommand: "nuxt generate", outputDir: ".output/public", outputGlob: null, entry: "/app.vue", htmlEntry: null },
  "remix": { tier: 2, installCommand: "pnpm install --frozen-lockfile", buildCommand: "remix vite:build", outputDir: "build/client", outputGlob: null, entry: "/app/routes/_index.tsx", htmlEntry: null },
};
