// pipeline/import.mjs
//
// Reads the 16 example directories from `examples/`, generates the synthetic
// blank templates (DEV-2499, see blank-starters.mjs), and emits versioned
// starter buckets (DEV-2213) plus the catalog index:
//
//   apps/authoring/public/starter-examples/<bucket>/manifest.json
//   apps/authoring/public/starter-examples/<bucket>/<framework>.json
//   runner/catalog.json   — index only (no files); the authoring UI
//                           lazy-fetches full artifacts per bucket on select.
//
// Bucket keys are major-only ("15".."18") plus "next", each pinned to a
// concrete Handsontable version (npm latest stable of the major; newest -next
// build for "next") with the pnpm lockfile re-resolved to match. Membership is
// filtered by frameworks.json `minCoreMajor` — a below-floor starter is not
// emitted rather than emitted broken.
//
// Run (from runner/):
//   node pipeline/import.mjs                          all buckets from ../examples + index
//   node pipeline/import.mjs --bucket=18              one bucket from ../examples
//   node pipeline/import.mjs --bucket=15 --source=<dir> --ref=prod-examples/15
//   node pipeline/import.mjs --index                  rebuild catalog.json from bucket dirs
//   node pipeline/import.mjs --synthetic              regenerate ONLY the blank templates,
//                                                     in every bucket already on disk
//
// Needs network (npm registry + pnpm lockfile resolution); `--synthetic` needs it
// only for its three small lockfiles, taking each bucket's pinned Handsontable
// version from the manifest already on disk. Build artifacts,
// npm/Yarn lockfiles, node_modules, CodeSandbox metadata, and binary assets are
// excluded; binary assets are recorded (path only) so a later stage can copy
// them verbatim. pnpm locks are preserved, re-resolved against the pinned
// version, and inlined so sessions at the bucket version get frozen installs.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { blankStarterFiles } from "./blank-starters.mjs";
import {
  applyStarterOverrides,
  lintStarterOptionShapes,
  starterOverrideIds,
} from "./starter-overrides.mjs";
import {
  assertStarterBucket,
  resolveLatestStableMajor,
  resolveStarterHotVersion,
} from "./starter-import-config.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RUNNER_DIR = path.resolve(__dirname, "..");
const REPO_ROOT = path.resolve(RUNNER_DIR, "..");
const EXAMPLES_DIR = path.join(REPO_ROOT, "examples");
const OUT_DIR = path.join(RUNNER_DIR, "apps", "authoring", "public", "starter-examples");
const INDEX_PATH = path.join(RUNNER_DIR, "catalog.json");
const CONFIG = JSON.parse(
  fs.readFileSync(path.join(RUNNER_DIR, "config", "frameworks.json"), "utf8"),
);
const FRAMEWORKS = CONFIG.frameworks;

// Lowest major any bucket is generated for. Empirically verified range starts
// at 15 (ADR-0021 decision 10); mirrors DEFAULT_MIN_MAJOR in
// packages/runtime/src/version.ts — this script stays dependency-free, so the
// constant cannot be imported from the (possibly unbuilt) runtime dist.
const MIN_BUCKET_MAJOR = 15;

// Directories never copied into a template.
const EXCLUDE_DIRS = new Set([
  "node_modules",
  ".git",
  ".cache",
  "dist",
  "build",
  "out", // Next.js static-export output (`outputDir: "out"` for the staticExport frameworks)
  ".next",
  ".nuxt",
  ".output",
  ".astro",
  ".angular", // Angular CLI build cache (ng serve/build run locally in the example)
  ".vite",
  ".codesandbox", // CodeSandbox-specific config; we are replacing CodeSandbox
  ".devcontainer",
  ".vscode",
  ".changelog-prs-cache",
]);

// npm and Yarn lockfiles are never copied. The catalog preserves pnpm locks so
// bucket-version sessions can use deterministic frozen installs.
const EXCLUDE_FILES = new Set([
  "package-lock.json",
  "yarn.lock",
  ".DS_Store",
  "next-env.d.ts", // regenerated by `next dev` in the container; gitignored in the starters
]);

// Extensions treated as binary assets (recorded, not inlined as text).
const BINARY_EXT = new Set([
  ".ico", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif",
  ".woff", ".woff2", ".ttf", ".eot", ".otf",
  ".mp4", ".webm", ".mp3", ".wav", ".pdf", ".zip",
]);

const MAX_TEXT_BYTES = 512 * 1024; // skip pathologically large text files

function walk(dir, base = dir, acc = []) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const rel = path.relative(base, full).split(path.sep).join("/");
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      if (EXCLUDE_DIRS.has(name)) continue;
      walk(full, base, acc);
    } else if (stat.isFile()) {
      if (EXCLUDE_FILES.has(name)) continue;
      acc.push({ rel, full, size: stat.size });
    }
  }
  return acc;
}

function looksBinary(buf) {
  // Heuristic: a NUL byte in the first 8 KB → binary.
  const n = Math.min(buf.length, 8192);
  for (let i = 0; i < n; i++) if (buf[i] === 0) return true;
  return false;
}

function normalizeEol(text) {
  return text.replace(/\r\n/g, "\n");
}

// Mirrors isHandsontablePackage in packages/runtime/src/version.ts (this
// script stays dependency-free). import.test.mjs pins the two implementations
// together by asserting the runtime's applyHandsontableVersion is a byte-level
// no-op on emitted artifacts.
const NEVER_REWRITE = new Set(["@handsontable/pikaday"]);
const isHandsontablePackage = (name) => name.includes("handsontable") && !NEVER_REWRITE.has(name);

/**
 * Pin every Handsontable dependency in /package.json to `hotVersion`,
 * serialized byte-for-byte the way the runtime's applyHandsontableVersion
 * would re-serialize it. That byte identity is load-bearing: the runtimes
 * re-apply the rewrite unconditionally at mount, and the Tier-2 frozen-install
 * fast path only opens when the mounted package.json still hashes to the baked
 * sourceDependencyFingerprint.
 */
export function pinHandsontableDependencies(files, hotVersion) {
  const raw = files["/package.json"];
  if (raw === undefined) return files;
  const pkg = JSON.parse(raw);
  const rewrite = (deps) => {
    if (!deps) return deps;
    return Object.fromEntries(
      Object.entries(deps).map(([name, range]) =>
        isHandsontablePackage(name) ? [name, hotVersion] : [name, range],
      ),
    );
  };
  const next = { ...pkg, dependencies: rewrite(pkg.dependencies) };
  return { ...files, "/package.json": JSON.stringify(next, null, 2) + "\n" };
}

/**
 * Re-resolve the starter's pnpm lockfile against the pinned package.json so a
 * frozen install at the bucket version succeeds. The committed lock (resolved
 * from "latest" at some point in time) is used as the starting point to keep
 * resolution incremental.
 */
function defaultRegenLockfile({ framework, files }) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), `starter-lock-${framework.replace(/[^a-z0-9]+/gi, "-")}-`));
  try {
    fs.writeFileSync(path.join(dir, "package.json"), files["/package.json"]);
    if (files["/pnpm-lock.yaml"]) fs.writeFileSync(path.join(dir, "pnpm-lock.yaml"), files["/pnpm-lock.yaml"]);
    if (files["/.npmrc"]) fs.writeFileSync(path.join(dir, ".npmrc"), files["/.npmrc"]);
    execFileSync(
      "corepack",
      ["pnpm", "install", "--lockfile-only", "--ignore-scripts", "--ignore-workspace"],
      { cwd: dir, stdio: "inherit" },
    );
    return fs.readFileSync(path.join(dir, "pnpm-lock.yaml"), "utf8");
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function collectExample(framework, sourceDir) {
  const cfg = FRAMEWORKS[framework];
  const dir = path.join(sourceDir, framework);
  if (!fs.existsSync(dir)) {
    throw new Error(`example directory not found: ${dir}`);
  }

  const files = {};
  const assets = [];
  const skipped = [];

  for (const { rel, full, size } of walk(dir)) {
    const ext = path.extname(rel).toLowerCase();
    if (BINARY_EXT.has(ext)) {
      assets.push(rel);
      continue;
    }
    if (size > MAX_TEXT_BYTES) {
      skipped.push({ path: rel, reason: `>${MAX_TEXT_BYTES}B` });
      continue;
    }
    const buf = fs.readFileSync(full);
    if (looksBinary(buf)) {
      assets.push(rel);
      continue;
    }
    files[`/${rel}`] = normalizeEol(buf.toString("utf8"));
  }

  return { cfg, files, assets, skipped };
}

/** frameworks.json-derived fields shared by bucket artifacts and the index. */
function configEntry(framework) {
  const cfg = FRAMEWORKS[framework];
  return {
    framework,
    displayName: cfg.displayName,
    tier: cfg.tier,
    engine: cfg.engine ?? (cfg.tier === 2 ? "container" : "sandpack"),
    sandpackTemplate: cfg.sandpackTemplate ?? null,
    sandpackEnvironment: cfg.sandpackEnvironment ?? null,
    container: cfg.container ?? null,
    htWrappers: cfg.htWrappers,
    entry: `/${cfg.entry}`,
    htmlEntry: cfg.htmlEntry ? `/${cfg.htmlEntry}` : null,
    devCommand: cfg.devCommand,
    buildCommand: cfg.buildCommand,
    outputDir: cfg.outputDir,
    outputGlob: cfg.outputGlob ?? null,
    staticExport: cfg.staticExport ?? false,
    spaMode: cfg.spaMode ?? false,
    port: cfg.port,
    installCommand: cfg.installCommand,
    minCoreMajor: cfg.minCoreMajor ?? null,
  };
}

/** Frameworks that exist in a bucket: "next" carries all, majors respect the floor. */
export function bucketFrameworks(bucket) {
  return Object.keys(FRAMEWORKS).filter((framework) => {
    if (bucket === "next") return true;
    const floor = FRAMEWORKS[framework].minCoreMajor ?? 0;
    return floor <= Number(bucket);
  });
}

export async function importStarters({
  sourceDir = EXAMPLES_DIR,
  bucket,
  ref = "master",
  outDir = OUT_DIR,
  hotVersion,
  regenLockfile = defaultRegenLockfile,
  fetchImpl,
}) {
  assertStarterBucket(bucket);
  hotVersion = hotVersion ?? (await resolveStarterHotVersion({ bucket, fetchImpl }));
  const frameworks = bucketFrameworks(bucket);
  const bucketOutDir = path.join(outDir, bucket);
  const manifest = [];
  const problems = [];

  // Reset only the selected bucket. Other version snapshots must survive.
  fs.rmSync(bucketOutDir, { recursive: true, force: true });
  fs.mkdirSync(bucketOutDir, { recursive: true });

  for (const framework of frameworks) {
    // A synthetic starter (the blank templates, DEV-2499) has no directory under
    // examples/ — its files are generated per bucket, because the pre-17 styling
    // idiom differs from 17+ (see blank-starters.mjs). Everything below this
    // line treats both sources identically.
    const { files: rawFiles, assets, skipped } = FRAMEWORKS[framework].synthetic
      ? { files: blankStarterFiles(framework, { bucket }), assets: [], skipped: [] }
      : collectExample(framework, sourceDir);
    // Per-major starter source (DEV-2545). The bucket's `examples/` tree comes
    // from a frozen prod-examples/<major> branch, so date/time cell options and
    // the values they parse are rewritten here to the shape the bucket's
    // Handsontable major supports. Runs BEFORE the version pin: the pinned
    // /package.json must stay byte-identical to what the runtime's
    // applyHandsontableVersion re-serializes (see pinHandsontableDependencies),
    // so the pin gets the last word.
    const { files: overlaid } = applyStarterOverrides(framework, rawFiles, { bucket });
    // The rows that GOVERN this artifact, not the subset that happened to
    // mutate bytes on this run — a row is a no-op whenever the source branch
    // already carries the bucket-correct shape, and recording only mutations
    // would leave the artifact the overlay exists for describing itself as
    // untouched.
    const overrides = starterOverrideIds(framework, bucket);
    let files = pinHandsontableDependencies(overlaid, hotVersion);
    // Synthetic starters ship no lockfile of their own, but they still get one
    // resolved here: without it the snapshot builder's frozen install fails and
    // falls back to a fresh resolve, so a demo saved a year from now would build
    // against whatever vite/react resolve to then.
    if (files["/pnpm-lock.yaml"] !== undefined || FRAMEWORKS[framework].synthetic) {
      const lock = regenLockfile({ framework, files });
      if (lock !== undefined) files = { ...files, "/pnpm-lock.yaml": lock };
    }

    const entry = {
      ...configEntry(framework),
      htCoreRange: hotVersion,
      fileCount: Object.keys(files).length,
      overrides,
      assets,
      skipped,
      files,
    };

    // The overlay makes bucket content a two-place question (source ref + the
    // registry), so a bucket that would emit an option shape its major does not
    // support must fail GENERATION rather than ship misrendering.
    problems.push(...lintStarterOptionShapes(framework, files, { bucket }));

    // Sanity: every artifact must have package.json and its declared entry file.
    if (!files["/package.json"]) problems.push(`${framework}: missing package.json`);
    if (!files[entry.entry] && !assets.includes(entry.entry.slice(1))) {
      problems.push(`${framework}: declared entry ${entry.entry} not found among files`);
    }
    if (entry.fileCount === 0) problems.push(`${framework}: no files imported`);

    fs.writeFileSync(path.join(bucketOutDir, `${framework}.json`), JSON.stringify(entry) + "\n");

    manifest.push({
      framework,
      displayName: entry.displayName,
      tier: entry.tier,
      engine: entry.engine,
      minCoreMajor: entry.minCoreMajor,
      overrides,
    });
  }

  fs.writeFileSync(
    path.join(bucketOutDir, "manifest.json"),
    JSON.stringify(
      {
        bucket,
        sourceRef: ref,
        // Bucket content = this source ref PLUS the per-major overlay applied
        // on top of it (pipeline/starter-overrides.mjs). Recorded per starter
        // in `examples[].overrides` so an artifact is self-describing.
        generatedFrom: "handsontable/examples examples/",
        hotVersion,
        count: manifest.length,
        examples: manifest,
      },
      null,
      2,
    ) + "\n",
  );

  console.log(
    `[import] bucket ${bucket} (${ref}, handsontable ${hotVersion}): ` +
      `${manifest.length} starters → ${path.relative(REPO_ROOT, bucketOutDir)}`,
  );
  if (problems.length) {
    throw new Error(`[import] bucket ${bucket} validation problems:\n  - ` + problems.join("\n  - "));
  }
  return { bucket, hotVersion, count: manifest.length };
}

/** Bucket keys that have a manifest on disk. */
function bucketsOnDisk(outDir) {
  return (fs.existsSync(outDir) ? fs.readdirSync(outDir) : [])
    .filter((name) => fs.existsSync(path.join(outDir, name, "manifest.json")))
    .sort(compareBuckets);
}

/**
 * Regenerate ONLY the synthetic starters, into the buckets already on disk.
 *
 * A full `importStarters` run re-collects all 16 real starters and re-resolves
 * all 16 pnpm lockfiles, which takes several minutes and a warm pnpm store.
 * Changing a blank template needs none of that: each bucket manifest already
 * records the version to pin to, and only three small lockfiles have to be
 * resolved. So this patches the synthetic artifacts in place and rewrites the
 * manifest rows, leaving every real starter artifact byte-identical.
 *
 * CI still regenerates everything through `importStarters`; this is the local
 * path for iterating on the templates themselves.
 */
export function importSyntheticStarters({ outDir = OUT_DIR, regenLockfile = defaultRegenLockfile } = {}) {
  const synthetic = Object.keys(FRAMEWORKS).filter((f) => FRAMEWORKS[f].synthetic);
  if (!synthetic.length) throw new Error("[import] no synthetic frameworks configured");

  const buckets = bucketsOnDisk(outDir);
  if (!buckets.length) {
    throw new Error(`[import] no starter buckets found under ${outDir}; run a full import first`);
  }

  for (const bucket of buckets) {
    const manifestPath = path.join(outDir, bucket, "manifest.json");
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    const hotVersion = manifest.hotVersion;
    if (!hotVersion) throw new Error(`[import] bucket ${bucket}: manifest has no hotVersion`);

    const existing = new Map(manifest.examples.map((row) => [row.framework, row]));
    const rows = [];

    // Rebuild the row list in frameworks.json order rather than appending, so a
    // synthetic-only run leaves the manifest in the same order a full import
    // would produce.
    for (const framework of bucketFrameworks(bucket)) {
      if (!FRAMEWORKS[framework].synthetic) {
        const row = existing.get(framework);
        if (row) rows.push(row);
        continue;
      }

      let files = pinHandsontableDependencies(
        blankStarterFiles(framework, { bucket }),
        hotVersion,
      );
      const lock = regenLockfile({ framework, files });
      if (lock !== undefined) files = { ...files, "/pnpm-lock.yaml": lock };
      const entry = {
        ...configEntry(framework),
        htCoreRange: hotVersion,
        fileCount: Object.keys(files).length,
        // Synthetic starters are generated per bucket already (blank-starters.mjs
        // branches on the bucket itself), so the overlay has no rows for them.
        overrides: [],
        assets: [],
        skipped: [],
        files,
      };
      if (!files[entry.entry]) {
        throw new Error(`[import] ${framework}: declared entry ${entry.entry} not generated`);
      }
      fs.writeFileSync(path.join(outDir, bucket, `${framework}.json`), JSON.stringify(entry) + "\n");
      rows.push({
        framework,
        displayName: entry.displayName,
        tier: entry.tier,
        engine: entry.engine,
        minCoreMajor: entry.minCoreMajor,
        overrides: [],
      });
    }

    fs.writeFileSync(
      manifestPath,
      JSON.stringify({ ...manifest, count: rows.length, examples: rows }, null, 2) + "\n",
    );
    console.log(
      `[import] bucket ${bucket} (handsontable ${hotVersion}): ` +
        `${synthetic.length} synthetic starters regenerated`,
    );
  }

  return { buckets, synthetic };
}

/** Sort bucket keys numerically with "next" last. */
function compareBuckets(a, b) {
  if (a === "next") return 1;
  if (b === "next") return -1;
  return Number(a) - Number(b);
}

/**
 * Rebuild runner/catalog.json — the index the authoring UI bundles: bucket
 * list plus the version-independent, files-free rows the picker, the version
 * dropdown, and BUILD_CONFIG generation need. Deterministic from
 * frameworks.json + the bucket directories, so the CI publish job can rebuild
 * it after merging per-bucket artifacts.
 */
export function writeCatalogIndex({ outDir = OUT_DIR, indexPath = INDEX_PATH } = {}) {
  const buckets = bucketsOnDisk(outDir);
  if (!buckets.length) {
    throw new Error(`[import] no starter buckets found under ${outDir}; run a bucket import first`);
  }

  const catalog = {
    generatedFrom: "handsontable/examples examples/",
    buckets,
    tiers: {
      "1": "client-side (Sandpack, in-browser bundler)",
      "2": "SSR/meta-framework (Cloudflare Sandbox container)",
    },
    examples: Object.keys(FRAMEWORKS).map(configEntry),
  };
  fs.writeFileSync(indexPath, JSON.stringify(catalog, null, 2) + "\n");
  console.log(`[import] wrote ${path.relative(REPO_ROOT, indexPath)} (buckets: ${buckets.join(", ")})`);
  return catalog;
}

async function main() {
  const args = process.argv.slice(2);
  const get = (name) => args.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);
  const sourceDir = get("source") ?? EXAMPLES_DIR;
  const ref = get("ref") ?? "master";
  const bucket = get("bucket");

  if (args.includes("--index")) {
    writeCatalogIndex({});
    return;
  }
  if (args.includes("--synthetic")) {
    importSyntheticStarters({});
    writeCatalogIndex({});
    return;
  }
  if (bucket) {
    await importStarters({ sourceDir, bucket, ref });
    return;
  }

  // Full local regeneration: every release bucket plus next, all synthesized
  // from the checked-out examples/ tree. CI instead imports each bucket from
  // its prod-examples/<major> branch when one exists.
  const latestMajor = await resolveLatestStableMajor();
  const buckets = [];
  for (let major = MIN_BUCKET_MAJOR; major <= latestMajor; major++) buckets.push(String(major));
  buckets.push("next");
  for (const b of buckets) await importStarters({ sourceDir, bucket: b, ref });
  writeCatalogIndex({});
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(`[import] ${error.message}`);
    process.exitCode = 1;
  });
}
