// Turning a theme into files in the demo (DEV-2047).
//
// Uses Handsontable's JavaScript theme API — registerTheme / params /
// setColorScheme / setDensityType, as documented on the "Theme customization"
// page and as theme-builder itself does. A theme is a real object the grid is
// given, not a pile of CSS variables shadowing one.
//
// That means two things have to land in the example: a module that builds the
// theme, and a reference to it wherever the grid is constructed. The second is
// the awkward half — `new Handsontable(el, {…})`, `<HotTable theme={…}>` and
// Angular's settings object are all different — so the wiring is done by
// recognising those specific shapes, and when none of them match the panel
// says which line to add instead of guessing and corrupting the file.
//
// Several starters already do this by hand (`theme={antTableTheme}`,
// `.setColorScheme("light")`), which is a good sign the generated code reads
// like something a person would have written.

import { googleFontFamily, isPristine, type ThemeState } from "./vocabulary.js";


/** Files a demo may use as its HTML entry, most specific first. */

const nonEmpty = (record: Record<string, string>) =>
  Object.entries(record).filter(([, v]) => v.trim().length > 0);

/** The generated theme module, at a fixed path so regenerating replaces it. */
export const THEME_MODULE_BASENAME = "handsontable-theme";
const MARKER = "handsontable-theme";

const BASE_THEME_IMPORT: Record<string, string> = {
  main: "mainTheme",
  horizon: "horizonTheme",
  classic: "classicTheme",
};

const quote = (v: string) => `'${v.replace(/'/g, "\\'")}'`;

/** Dotted palette keys -> the nested `colors` object `.params()` expects. */
function nestPalette(entries: [string, string][]): Record<string, unknown> {
  const nested: Record<string, unknown> = {};
  for (const [key, value] of entries) {
    const dot = key.indexOf(".");
    if (dot === -1) {
      nested[key] = value;
      continue;
    }
    const bucket = (nested[key.slice(0, dot)] ??= {}) as Record<string, string>;
    bucket[key.slice(dot + 1)] = value;
  }
  return nested;
}

function renderObject(value: unknown, indent: string): string {
  if (typeof value === "string") return quote(value);
  const entries = Object.entries(value as Record<string, unknown>);
  if (entries.length === 0) return "{}";
  const inner = entries
    .map(([k, v]) => `${indent}  ${/^[A-Za-z_$][\w$]*$/.test(k) ? k : quote(k)}: ${renderObject(v, `${indent}  `)},`)
    .join("\n");
  return `{\n${inner}\n${indent}}`;
}

/**
 * The theme module written into the demo.
 *
 * Mirrors the documented API exactly: register a base theme, then layer the
 * palette and token overrides through `.params({ colors, tokens })`, the
 * colour scheme through `.setColorScheme()` and the density through
 * `.setDensityType()`.
 */
export function buildThemeModule(state: ThemeState, typescript: boolean): string {
  const base = BASE_THEME_IMPORT[state.tokens] ?? "mainTheme";
  const palette = nonEmpty(state.palette);
  const tokens = nonEmpty(state.params);
  const density = nonEmpty(state.densitySizes);
  const font = googleFontFamily(state.params.fontFamily);

  const lines = [
    "// Generated by the demo runner's theme panel. Edit freely — it is a normal",
    "// module, and regenerating replaces it.",
    `import { ${base}, registerTheme } from 'handsontable/themes';`,
  ];

  const usesColorsPreset = state.colors !== "main";
  if (usesColorsPreset) {
    lines.push(`import colorsPreset from 'handsontable/themes/static/variables/colors/${state.colors}';`);
  }
  lines.push("", `export const customTheme = registerTheme(${base});`, "");

  const colorsObject = { ...(palette.length ? nestPalette(palette) : {}) };
  const tokensObject: Record<string, unknown> = Object.fromEntries(tokens);
  // Density sizes are density tokens; the documented setter only takes a type,
  // so per-size values go through params alongside the rest.
  for (const [name, value] of density) tokensObject[`density${name[0]!.toUpperCase()}${name.slice(1)}`] = value;

  const hasColors = usesColorsPreset || Object.keys(colorsObject).length > 0;
  if (hasColors || Object.keys(tokensObject).length > 0) {
    const parts: string[] = [];
    if (hasColors) {
      const spread = usesColorsPreset ? "\n    ...colorsPreset," : "";
      const rest = Object.entries(colorsObject)
        .map(([k, v]) => `\n    ${k}: ${renderObject(v, "    ")},`)
        .join("");
      parts.push(`  colors: {${spread}${rest}\n  },`);
    }
    if (Object.keys(tokensObject).length > 0) {
      parts.push(`  tokens: ${renderObject(tokensObject, "  ")},`);
    }
    lines.push("customTheme.params({", ...parts, "});", "");
  }

  lines.push(`customTheme.setColorScheme('${state.colorScheme}');`);
  lines.push(`customTheme.setDensityType('${state.density}');`);

  if (font) {
    lines.push(
      "",
      "// The font has to exist in the page before the grid can use it.",
      "const link = document.createElement('link');",
      `link.rel = 'stylesheet';`,
      `link.href = 'https://fonts.googleapis.com/css2?family=${encodeURIComponent(font).replace(/%20/g, "+")}&display=swap';`,
      "document.head.appendChild(link);",
    );
  }

  void typescript;
  return `${lines.join("\n")}\n`;
}

/**
 * The code to copy into a real application.
 *
 * Identical to what is written into the demo, and that is the point: with the
 * JS API there is no gap between "what the playground did" and "what you paste
 * into your app" — the panel is not translating between two mechanisms.
 */
export function buildThemeSnippet(state: ThemeState): string {
  return `${buildThemeModule(state, true)}\n// then hand it to the grid:  <HotTable theme={customTheme} … />\n`;
}

export interface ThemeFileChange {
  path: string;
  contents: string;
}

/** Where the grid is built, and how a theme is handed to it. */
interface WireTarget {
  path: string;
  contents: string;
}

const IMPORT_LINE = (dir: string) => `import { customTheme } from '${dir}${THEME_MODULE_BASENAME}'; // ${MARKER}`;

/**
 * Attach the theme where the grid is constructed.
 *
 * Three shapes cover every starter in the catalog:
 *   `<HotTable …>`                     — React and Vue wrappers, add a prop
 *   `new Handsontable(el, { … })`      — vanilla JS/TS and Astro, add a setting
 *   `const gridSettings … = { … }`     — Angular, add a setting
 *
 * Anything else is left alone. A theme that fails to apply is a puzzle; a
 * component file mangled by an over-eager regex is a lost afternoon.
 */
function wireTheme(files: Record<string, string>): WireTarget | null {
  const candidates = Object.entries(files)
    .filter(([path]) => /\.(t|j)sx?$|\.vue$|\.astro$/.test(path))
    .sort(([a], [b]) => a.length - b.length);

  for (const [path, source] of candidates) {
    if (typeof source !== "string") continue;
    // Already wired by a previous apply: report it as wired rather than
    // telling the user to add a line that is sitting in the file.
    if (source.includes(MARKER)) return { path, contents: source };

    let next: string | null = null;

    // 1. JSX/Vue wrapper element. Replace an existing theme prop rather than
    //    adding a second one — several starters already set their own.
    if (/<(HotTable|hot-table)\b/.test(source)) {
      next = /\btheme=\{[^}]*\}/.test(source)
        ? source.replace(/\btheme=\{[^}]*\}/, "theme={customTheme}")
        : source.replace(/<(HotTable|hot-table)\b/, "<$1 theme={customTheme}");
    } else if (/new Handsontable\(\s*[A-Za-z_$][\w$]*\s*,\s*\{/.test(source)) {
      // 2. Vanilla settings object.
      next = source.replace(/(new Handsontable\(\s*[A-Za-z_$][\w$]*\s*,\s*\{)/, "$1\n  theme: customTheme,");
    } else if (/gridSettings[^=]*=\s*\{/.test(source)) {
      // 3. Angular's settings object.
      next = source.replace(/(gridSettings[^=]*=\s*\{)/, "$1\n    theme: customTheme,");
    }

    if (!next) continue;

    // Relative path from the edited file back to the module at the root.
    const depth = path.split("/").filter(Boolean).length - 1;
    const dir = depth > 0 ? "../".repeat(depth) : "./";
    return { path, contents: `${IMPORT_LINE(dir)}\n${next}` };
  }

  return null;
}

/** Does the example look like TypeScript? Decides the module's extension. */
function isTypescript(files: Record<string, string>): boolean {
  return Object.keys(files).some((p) => /\.tsx?$/.test(p));
}

export function themeModulePath(files: Record<string, string>): string {
  return `/${THEME_MODULE_BASENAME}.${isTypescript(files) ? "ts" : "js"}`;
}

/**
 * The file edits that apply `state` to a demo: the theme module, plus the one
 * line that hands it to the grid when we can see where that happens.
 */
export function buildThemeChanges(
  files: Record<string, string>,
  state: ThemeState,
): { changes: ThemeFileChange[]; linked: boolean } {
  const changes: ThemeFileChange[] = [
    { path: themeModulePath(files), contents: buildThemeModule(state, isTypescript(files)) },
  ];

  const wired = wireTheme(files);
  if (wired) changes.push({ path: wired.path, contents: wired.contents });
  return { changes, linked: Boolean(wired) };
}

/** Remove the theme again: an inert module, and the wiring taken back out. */
export function buildResetChanges(files: Record<string, string>): ThemeFileChange[] {
  const changes: ThemeFileChange[] = [];
  for (const [path, source] of Object.entries(files)) {
    if (typeof source !== "string" || !source.includes(MARKER)) continue;
    changes.push({
      path,
      contents: source
        .split("\n")
        .filter((line) => !line.includes(MARKER))
        .join("\n")
        .replace(/\s*theme=\{customTheme\}/g, "")
        .replace(/\n\s*theme: customTheme,/g, ""),
    });
  }
  changes.push({
    path: themeModulePath(files),
    contents: "// Theme cleared.\nexport const customTheme = undefined;\n",
  });
  return changes;
}

/** Shown when no grid construction was recognised. */
export function manualImportHint(files: Record<string, string>): string {
  return `import { customTheme } from '.${themeModulePath(files).replace(/\.(t|j)s$/, "")}';  →  theme={customTheme}`;
}

export { isPristine };
