// Turning a theme into files in the demo (DEV-2047).
//
// Styling a demo has to survive being downloaded, shared and reopened, so it
// cannot live in the panel's memory: it is written into the example as real
// files, the same way the editor and the AI assistant write edits, and the
// preview HMRs it like any other change.
//
// Two routes exist, and the choice matters:
//
//   1. JS  — `registerTheme()` from `handsontable/themes`, then pass the theme
//            to the instance. This is what theme-builder does, and what its
//            code export emits. It also means editing whichever component
//            constructs the grid — different in React, Vue, Angular, Next,
//            Nuxt and plain JS, and brittle to do by regex across a dozen
//            starter layouts.
//   2. CSS — override the `--ht-*` custom properties the theme is built from.
//            Handsontable's own "Theme customization" docs document every
//            token in both forms, so this is a supported route, not a hack.
//            One file, identical for every framework, no component code
//            touched, and it composes with whatever the example already does.
//
// This uses CSS to *apply*, and offers the JS snippet to *copy* — because the
// question a user asks after styling a demo is "how do I do this in my app?",
// and there the answer is theme-builder's registerTheme call.

import { cssVariable, isPristine, themeClass, type ThemeState } from "./vocabulary.js";

/** The generated stylesheet, kept at a fixed path so regenerating replaces it. */
export const THEME_CSS_PATH = "/handsontable-theme.css";
const STYLE_MARKER = "handsontable-theme";

/** Files a demo may use as its HTML entry, most specific first. */
const HTML_ENTRIES = ["/index.html", "/public/index.html", "/src/index.html"];

export function buildThemeCss(state: ThemeState): string {
  const entries = Object.entries(state.params).filter(([, v]) => v.trim().length > 0);
  const selector = `.${themeClass(state)}`;

  const lines = [
    "/* Generated by the demo runner's theme panel.",
    " * Edit freely — it is a normal stylesheet, and regenerating replaces it.",
    ` * Preset: tokens=${state.tokens} colors=${state.colors} icons=${state.icons}`,
    ` *         density=${state.density} colorScheme=${state.colorScheme}`,
    " */",
    "",
  ];

  if (entries.length > 0) {
    lines.push(`${selector} {`);
    for (const [name, value] of entries) lines.push(`  ${cssVariable(name)}: ${value};`);
    lines.push("}", "");
  }

  if (state.density !== "default") {
    lines.push(
      `/* Density preset: ${state.density}. The density tokens are grouped under`,
      " * --ht-density-*; switching preset classes is the documented way to move",
      " * between compact / default / comfortable. */",
      `${selector} { --ht-density: ${state.density}; }`,
      "",
    );
  }

  return lines.join("\n");
}

/**
 * The snippet theme-builder itself exports: register the theme and hand it to
 * the grid. Shown in the panel to copy into a real application, where a
 * stylesheet override is not always the right answer.
 */
export function buildThemeSnippet(state: ThemeState): string {
  const params = Object.entries(state.params).filter(([, v]) => v.trim().length > 0);
  const paramLines = params.length
    ? `\n\nconst theme = getTheme('custom-theme')?.params({\n${
      params.map(([k, v]) => `  ${k}: '${v.replace(/'/g, "\\'")}',`).join("\n")
    }\n});`
    : "\n\nconst theme = getTheme('custom-theme');";

  return `import { registerTheme, getTheme } from 'handsontable/themes';
import tokens from 'handsontable/themes/static/variables/tokens/${state.tokens}';
import colors from 'handsontable/themes/static/variables/colors/${state.colors}';
import icons from 'handsontable/themes/static/variables/icons/${state.icons}';

registerTheme('custom-theme', {
  tokens,
  colors,
  icons,
  density: '${state.density}',
  colorScheme: '${state.colorScheme}',
});${paramLines}

// then pass it to the grid:  <HotTable theme={theme} … />`;
}

export interface ThemeFileChange {
  path: string;
  contents: string;
}

/**
 * The file edits that apply `state` to a demo.
 *
 * The stylesheet is always written. Getting the browser to load it is the part
 * that varies: an HTML entry can link it directly, which covers the Vite-based
 * starters; anything else (Next, Nuxt, Remix, Astro) needs one import line the
 * panel tells the user about rather than guessing at their entry file and
 * corrupting it.
 */
export function buildThemeChanges(
  files: Record<string, string>,
  state: ThemeState,
): { changes: ThemeFileChange[]; linked: boolean } {
  const changes: ThemeFileChange[] = [{ path: THEME_CSS_PATH, contents: buildThemeCss(state) }];

  const htmlPath = HTML_ENTRIES.find((p) => typeof files[p] === "string");
  if (!htmlPath) return { changes, linked: false };

  const html = files[htmlPath] as string;
  const link = `    <link rel="stylesheet" href="${THEME_CSS_PATH}" data-${STYLE_MARKER} />`;
  const marker = new RegExp(`\\n?[^\\n]*data-${STYLE_MARKER}[^\\n]*`, "g");
  const stripped = html.replace(marker, "");

  // Last stylesheet in <head> wins, so the link goes at its end — the theme is
  // an override of whatever the example already loads.
  const linked = stripped.includes("</head>")
    ? stripped.replace("</head>", `${link}\n  </head>`)
    : `${link}\n${stripped}`;

  changes.push({ path: htmlPath, contents: linked });
  return { changes, linked: true };
}

/** Remove the theme again: blank stylesheet, link taken out. */
export function buildResetChanges(files: Record<string, string>): ThemeFileChange[] {
  const changes: ThemeFileChange[] = [
    { path: THEME_CSS_PATH, contents: "/* Theme cleared. */\n" },
  ];
  const htmlPath = HTML_ENTRIES.find((p) => typeof files[p] === "string");
  if (htmlPath) {
    const marker = new RegExp(`\\n?[^\\n]*data-${STYLE_MARKER}[^\\n]*`, "g");
    changes.push({ path: htmlPath, contents: (files[htmlPath] as string).replace(marker, "") });
  }
  return changes;
}

/** One line for the frameworks whose entry we refuse to rewrite blind. */
export function manualImportHint(state: ThemeState): string {
  void state;
  return `import '.${THEME_CSS_PATH}';`;
}

export { isPristine };
