// Turning a theme into files in the demo (DEV-2047).
//
// Styling a demo has to survive being downloaded, shared and reopened, so it
// cannot live in the panel's memory: it is written into the example as real
// files, the same way the editor and the AI assistant write edits, and the
// preview HMRs it like any other change.
//
// Two routes exist, and the choice matters:
//
//   1. JS  — `registerTheme()` from `handsontable/themes`, then pass the theme
//            to the instance. This is what theme-builder does, and what its
//            code export emits. It also means editing whichever component
//            constructs the grid — different in React, Vue, Angular, Next,
//            Nuxt and plain JS, and brittle to do by regex across a dozen
//            starter layouts.
//   2. CSS — override the `--ht-*` custom properties the theme is built from.
//            Handsontable's own "Theme customization" docs document every
//            token in both forms, so this is a supported route, not a hack.
//            One file, identical for every framework, no component code
//            touched, and it composes with whatever the example already does.
//
// This uses CSS to *apply*, and offers the JS snippet to *copy* — because the
// question a user asks after styling a demo is "how do I do this in my app?",
// and there the answer is theme-builder's registerTheme call.

import {
  cssVariable,
  densityVariable,
  googleFontFamily,
  isPristine,
  paletteVariable,
  themeClass,
  type ThemeState,
} from "./vocabulary.js";

/** The generated stylesheet, kept at a fixed path so regenerating replaces it. */
export const THEME_CSS_PATH = "/handsontable-theme.css";
const STYLE_MARKER = "handsontable-theme";

/** Files a demo may use as its HTML entry, most specific first. */
const HTML_ENTRIES = ["/index.html", "/public/index.html", "/src/index.html"];

const nonEmpty = (record: Record<string, string>) =>
  Object.entries(record).filter(([, v]) => v.trim().length > 0);

/** A multi-word font family needs quoting to be an unambiguous CSS value;
 *  everything else is passed through exactly as typed, so `rgba()`, `var()`
 *  and `transparent` all still work. */
function cssValue(name: string, value: string): string {
  const trimmed = value.trim();
  if (name !== "fontFamily") return trimmed;
  if (/['"]/.test(trimmed) || !trimmed.includes(" ") || trimmed.includes(",")) return trimmed;
  return `'${trimmed}'`;
}

export function buildThemeCss(state: ThemeState): string {
  const selector = `.${themeClass(state)}`;
  const params = nonEmpty(state.params);
  const palette = nonEmpty(state.palette);
  const density = nonEmpty(state.densitySizes);

  const lines: string[] = [];

  // A bare family name means "fetch this from Google Fonts", which is what
  // theme-builder does when you type one. @import has to lead the file, so it
  // goes above even the banner comment's siblings — comments are allowed
  // before it, other rules are not.
  const font = googleFontFamily(state.params.fontFamily);
  if (font) {
    lines.push(
      `@import url('https://fonts.googleapis.com/css2?family=${encodeURIComponent(font).replace(/%20/g, "+")}&display=swap');`,
      "",
    );
  }

  lines.push(
    "/* Generated by the demo runner's theme panel.",
    " * Edit freely — it is a normal stylesheet, and regenerating replaces it.",
    ` * Preset: tokens=${state.tokens} colors=${state.colors} icons=${state.icons}`,
    ` *         density=${state.density} colorScheme=${state.colorScheme}`,
    " */",
    "",
  );

  if (palette.length > 0) {
    lines.push(
      "/* Colour ramps. Tokens derive from these, so recolouring the brand is",
      " * one edit here rather than a dozen token overrides. */",
      `${selector} {`,
    );
    for (const [key, value] of palette) lines.push(`  ${paletteVariable(key)}: ${value};`);
    lines.push("}", "");
  }

  if (params.length > 0) {
    lines.push(`${selector} {`);
    for (const [name, value] of params) lines.push(`  ${cssVariable(name)}: ${cssValue(name, value)};`);
    lines.push("}", "");
  }

  if (state.density !== "default" || density.length > 0) {
    lines.push(`/* Density: ${state.density}${density.length ? " + per-size overrides" : ""}. */`, `${selector} {`);
    if (state.density !== "default") lines.push(`  --ht-density: ${state.density};`);
    for (const [name, value] of density) lines.push(`  ${densityVariable(name)}: ${value};`);
    lines.push("}", "");
  }

  return lines.join("\n");
}

/**
 * The snippet theme-builder itself exports: register the theme and hand it to
 * the grid. Shown in the panel to copy into a real application, where a
 * stylesheet override is not always the right answer.
 */
export function buildThemeSnippet(state: ThemeState): string {
  const params = nonEmpty(state.params);
  const palette = nonEmpty(state.palette);
  const densitySizes = nonEmpty(state.densitySizes);
  const paramLines = params.length
    ? `\n\nconst theme = getTheme('custom-theme')?.params({\n${
      params.map(([k, v]) => `  ${k}: '${v.replace(/'/g, "\\'")}',`).join("\n")
    }\n});`
    : "\n\nconst theme = getTheme('custom-theme');";

  // Palette edits change the colours object the theme is built from, so they
  // belong in registerTheme rather than in .params() — and they have to be
  // NESTED there. `{ "primary.500": … }` is a flat key that means nothing to
  // the themes API; the shape it wants is `{ primary: { 500: … } }`.
  const colorsExpr = palette.length ? `{\n    ...colors,\n${renderPalette(palette)}  }` : "colors";

  const densityExpr = densitySizes.length
    ? `{\n    type: '${state.density}',\n    sizes: {\n${
      densitySizes.map(([k, v]) => `      ${k}: '${v.replace(/'/g, "\\'")}',`).join("\n")
    }\n    },\n  }`
    : `'${state.density}'`;

  return `import { registerTheme, getTheme } from 'handsontable/themes';
import tokens from 'handsontable/themes/static/variables/tokens/${state.tokens}';
import colors from 'handsontable/themes/static/variables/colors/${state.colors}';
import icons from 'handsontable/themes/static/variables/icons/${state.icons}';

registerTheme('custom-theme', {
  tokens,
  colors: ${colorsExpr},
  icons,
  density: ${densityExpr},
  colorScheme: '${state.colorScheme}',
});${paramLines}

// then pass it to the grid:  <HotTable theme={theme} … />`;
}

/** Dotted palette keys -> nested source, at registerTheme's indentation. */
function renderPalette(entries: [string, string][]): string {
  const nested: Record<string, Record<string, string> | string> = {};
  for (const [key, value] of entries) {
    const dot = key.indexOf(".");
    if (dot === -1) {
      nested[key] = value;
      continue;
    }
    const bucket = (nested[key.slice(0, dot)] ??= {}) as Record<string, string>;
    bucket[key.slice(dot + 1)] = value;
  }

  const quote = (v: string) => `'${v.replace(/'/g, "\\'")}'`;
  return Object.entries(nested)
    .map(([key, value]) =>
      typeof value === "string"
        ? `    ${key}: ${quote(value)},\n`
        : `    ${key}: {\n${
          Object.entries(value).map(([step, v]) => `      ${step}: ${quote(v)},`).join("\n")
        }\n    },\n`)
    .join("");
}

export interface ThemeFileChange {
  path: string;
  contents: string;
}

/**
 * The file edits that apply `state` to a demo.
 *
 * The stylesheet is always written. Getting the browser to load it is the part
 * that varies: an HTML entry can link it directly, which covers the Vite-based
 * starters; anything else (Next, Nuxt, Remix, Astro) needs one import line the
 * panel tells the user about rather than guessing at their entry file and
 * corrupting it.
 */
export function buildThemeChanges(
  files: Record<string, string>,
  state: ThemeState,
): { changes: ThemeFileChange[]; linked: boolean } {
  const changes: ThemeFileChange[] = [{ path: THEME_CSS_PATH, contents: buildThemeCss(state) }];

  const htmlPath = HTML_ENTRIES.find((p) => typeof files[p] === "string");
  if (!htmlPath) return { changes, linked: false };

  const html = files[htmlPath] as string;
  const link = `    <link rel="stylesheet" href="${THEME_CSS_PATH}" data-${STYLE_MARKER} />`;
  const marker = new RegExp(`\\n?[^\\n]*data-${STYLE_MARKER}[^\\n]*`, "g");
  const stripped = html.replace(marker, "");

  // Last stylesheet in <head> wins, so the link goes at its end — the theme is
  // an override of whatever the example already loads.
  const linked = stripped.includes("</head>")
    ? stripped.replace("</head>", `${link}\n  </head>`)
    : `${link}\n${stripped}`;

  changes.push({ path: htmlPath, contents: linked });
  return { changes, linked: true };
}

/** Remove the theme again: blank stylesheet, link taken out. */
export function buildResetChanges(files: Record<string, string>): ThemeFileChange[] {
  const changes: ThemeFileChange[] = [
    { path: THEME_CSS_PATH, contents: "/* Theme cleared. */\n" },
  ];
  const htmlPath = HTML_ENTRIES.find((p) => typeof files[p] === "string");
  if (htmlPath) {
    const marker = new RegExp(`\\n?[^\\n]*data-${STYLE_MARKER}[^\\n]*`, "g");
    changes.push({ path: htmlPath, contents: (files[htmlPath] as string).replace(marker, "") });
  }
  return changes;
}

/** One line for the frameworks whose entry we refuse to rewrite blind. */
export function manualImportHint(state: ThemeState): string {
  void state;
  return `import '.${THEME_CSS_PATH}';`;
}

export { isPristine };
