import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";

// Empirical starter-compatibility matrix (DEV-2102 / ADR-0021 decision 10):
// boots every starter in catalog.json at the latest patch of each supported
// Handsontable major (15-19) and records what actually breaks. Opt-in via
// E2E_STARTER_MATRIX=1 — this is not part of the deterministic PR suite; it
// spins ~50 real Tier-2 container sessions (the live-preview `Sandbox` class);
// a local run at --workers=2 --retries=2 took ~36 minutes.
//
// Prod only allows 5 concurrent live-preview containers
// (workers/api/wrangler.jsonc: Sandbox max_instances=5, separate from
// BuilderSandbox max_instances=3 which this test never touches). The
// e2e:matrix script runs at --workers=2 to leave headroom for real traffic —
// do not raise concurrency without checking current prod load.
//
// Run: E2E_BASE_URL=https://demos.handsontable.com pnpm e2e:matrix
// Report: pnpm e2e:matrix:report

const ENABLED = process.env.E2E_STARTER_MATRIX === "1";
const MAJORS = [15, 16, 17, 18, 19] as const;

type CatalogExample = {
  framework: string;
  displayName: string;
  engine: "sandpack" | "container";
  minCoreMajor: number | null;
};

const catalog = JSON.parse(readFileSync(new URL("../catalog.json", import.meta.url), "utf8")) as {
  examples: CatalogExample[];
};

/**
 * DEV-2734. `numericFormat` is invisible to every other check here: core types
 * it as bare `object`, so a wrong shape builds clean, and a misrendered cell
 * still counts as a rendered cell. The only oracle is the text in the cell.
 *
 * This is also the only suite that can run it. The deterministic PR suite reads
 * the committed bucket artifacts, which are regenerated by import-starters.yml
 * *after* a registry change merges, so a spec there would assert against stale
 * bytes; this one drives live prod at a real per-major version.
 *
 * 15/16 render a bare `87` on purpose — numbro cannot append a literal `%`
 * without also multiplying by 100. See the `example1:itemQuality` row.
 */
const example1NumericCells = (major: number) => [
  "$350,000",
  major >= 17 ? "87%" : "87",
];

// Console/page noise that isn't a real compatibility break. Extend as the
// matrix surfaces new false positives.
const NOISE = [
  /non-commercial|evaluation license/i,
  /Download the React DevTools/i,
  /favicon\.ico/i,
  /\[vite\] (connecting|connected)/i,
  /ERR_BLOCKED_BY_CLIENT|third-party cookie/i,
];
const isKnownNoise = (message: string) => NOISE.some((re) => re.test(message));

let latestByMajorPromise: Promise<Map<number, string>> | null = null;

// Resolve the latest stable patch release per major straight from npm — the
// app's own GET /api/versions slices results to 15 entries and can drop older
// majors, so it isn't a reliable source for "latest per major".
function resolveLatestByMajor(): Promise<Map<number, string>> {
  latestByMajorPromise ??= (async () => {
    const res = await fetch("https://registry.npmjs.org/handsontable", {
      headers: { Accept: "application/vnd.npm.install-v1+json" },
    });
    if (!res.ok) throw new Error(`npm registry responded ${res.status}`);
    const doc = (await res.json()) as { versions: Record<string, unknown> };
    const best = new Map<number, string>();
    for (const version of Object.keys(doc.versions)) {
      if (!/^\d+\.\d+\.\d+$/.test(version)) continue;
      const [major, minor, patch] = version.split(".").map(Number);
      const current = best.get(major);
      if (!current) {
        best.set(major, version);
        continue;
      }
      const [, currentMinor, currentPatch] = current.split(".").map(Number);
      if (minor > currentMinor || (minor === currentMinor && patch > currentPatch)) {
        best.set(major, version);
      }
    }
    return best;
  })();
  return latestByMajorPromise;
}

for (const entry of catalog.examples) {
  for (const major of MAJORS) {
    test(`matrix: ${entry.framework} @ ${major} [${entry.engine}]`, async ({ page, request }, testInfo) => {
      test.skip(!ENABLED, "set E2E_STARTER_MATRIX=1 to run the starter compatibility matrix");
      test.setTimeout(entry.engine === "container" ? 300_000 : 150_000);

      const byMajor = await resolveLatestByMajor();
      const version = byMajor.get(major);
      // A major with no stable npm release yet (e.g. 19 is pre-release as of
      // writing — dist-tags carry only `next`/`rc`) isn't a starter failure,
      // it's nothing to test yet. Skip rather than report a false breakage.
      test.skip(!version, `no stable handsontable release published for major ${major} yet`);
      if (!version) return;

      // A starter may declare a minimum core major (e.g. the UI-library starters
      // need the themes API added in core 17). Below-floor combos are
      // intentionally unavailable — the authoring app refuses to boot them and
      // shows a "try another version" message — so they are nothing to test as
      // bootable, not a breakage. Skip rather than assert a mounted grid.
      test.skip(
        entry.minCoreMajor != null && major < entry.minCoreMajor,
        `${entry.framework} requires Handsontable >= ${entry.minCoreMajor}; ${major} is intentionally unavailable`,
      );

      // Annotate immediately so a failing test still reports which version it
      // was testing — the report shouldn't say "unknown" just because the
      // test threw before reaching the end.
      testInfo.annotations.push({ type: "resolvedVersion", description: version }, { type: "engine", description: entry.engine });

      const consoleErrors: string[] = [];
      const pageErrors: string[] = [];
      const htRequestVersions: string[] = [];
      const sessions: { id: string; apiBase: string }[] = [];
      let postedHtVersion: string | null = null;

      page.on("console", (msg) => {
        if (msg.type() === "error") consoleErrors.push(msg.text());
      });
      page.on("pageerror", (err) => pageErrors.push(String(err)));
      page.on("request", (req) => {
        const url = req.url();
        const match = url.match(/handsontable[@/](\d+\.\d+\.\d+)/);
        if (match) htRequestVersions.push(match[1]);
        if (req.method() === "POST" && /\/api\/session$/.test(url)) {
          try {
            postedHtVersion = (JSON.parse(req.postData() ?? "{}") as { htVersion?: string }).htVersion ?? null;
          } catch {
            // ignore malformed payloads — absence just leaves postedHtVersion null
          }
        }
      });
      page.on("response", async (res) => {
        if (res.request().method() === "POST" && /\/api\/session$/.test(res.url()) && res.ok()) {
          const body = (await res.json().catch(() => null)) as { sessionId?: string } | null;
          if (body?.sessionId) sessions.push({ id: body.sessionId, apiBase: new URL(res.url()).origin });
        }
      });

      try {
        await page.goto(`/?example=${encodeURIComponent(entry.framework)}&v=${version}`);

        const preview = page.locator('section[aria-label="Preview"]');
        // Readiness comes off `data-preview-status` on the preview section
        // (PreviewPane.tsx), not off any visible text. It used to be the "Live"
        // label in a status strip that T2 removed — and before that, scoping to
        // that strip was itself a fix for `getByText` also matching the live
        // boot-log <pre> when a container's error text started with "Error:"
        // (mui, strict-mode violation). An attribute has neither failure mode.
        await expect(preview).toHaveAttribute("data-preview-status", "ready", {
          timeout: entry.engine === "container" ? 240_000 : 120_000,
        });

        // Container "Live" only means the dev server responded — the frame may
        // still be blank or mid-hydration (Next/Nuxt/Astro). The rendered grid
        // is the real functional check.
        const frame = page.frameLocator('iframe[title="Demo preview"]');
        const cells = frame.locator(".handsontable .htCore td");
        await expect
          .poll(async () => cells.count().catch(() => 0), { timeout: 60_000, intervals: [1_000] })
          .toBeGreaterThan(0);

        if (entry.framework === "example1") {
          // Read every cell and assert over the SET. A `filter({ hasText })`
          // locator would be a strict-mode violation: Handsontable renders the
          // same logical cell again in its clone_top/clone_left overlay tables,
          // which is why every other grid assertion here counts rather than
          // matches.
          const rendered = new Set(await cells.allInnerTexts());
          for (const expected of example1NumericCells(major)) {
            expect(rendered.has(expected), `numericFormat rendered ${expected} at ${major}`).toBe(true);
          }
        }

        const realErrors = [...consoleErrors, ...pageErrors].filter((e) => !isKnownNoise(e));
        expect(realErrors, `console/page errors:\n${realErrors.join("\n")}`).toEqual([]);

        let detectedVersion: string | null = null;
        if (entry.engine === "sandpack") {
          detectedVersion = htRequestVersions.find((v) => v === version) ?? htRequestVersions[0] ?? null;
        } else {
          expect(postedHtVersion, "requested handsontable version reached the container session").toBe(version);
          detectedVersion = await frame
            .locator("body")
            .evaluate(() => (window as unknown as { Handsontable?: { version?: string } }).Handsontable?.version ?? null)
            .catch(() => null);
        }

        testInfo.annotations.push({ type: "detectedVersion", description: detectedVersion ?? "unverified" });
        if (detectedVersion) expect(detectedVersion.startsWith(`${major}.`)).toBe(true);
      } finally {
        for (const { id, apiBase } of sessions) {
          await request.delete(`${apiBase}/api/session/${id}`).catch(() => {});
        }
      }
    });
  }
}
